favorite_animal = input("What is your favorite animal?\n>")
print("Your favorite animal is " + favorite_animal)
color = input("What color are they?\n>")
print("They are " + color)
live = input("Where do they live?\n>")
print("They live " + live)
fact = input("What is a fun fact about them?\n>")
print("A fun fact about them are " + fact)
sound = input("What sound so they make?\n>")
print("They make " + sound)