favorite_animal = input("What is your favorite animal?\n>")
color = input("What color are they?\n>")
live = input("Where do they live?\n>")
fact = input("What is a fun fact about them?\n>")
sound = input("What sound so they make?\n>")
print("Your favorite animal are" + favorite_animal + " ." + "They are " +  color + " ." + "They live in " +  live + " ," + " and a fun fact about them is " +  fact + " " + ". They make  " +  sound + " ")
